### ISSUE TITLE
NullPointerException with team requests

### ISSUE THREAD

**Issue by Sanjit1** [RaiderRobotix/blue-alliance-api-java-library#3]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.thebluealliance.api.v3.requests.APIResponse.getJson()' on a null object reference

My code:

TBA tba = new TBA("key");
                Team robot = new Team();
                TeamRequest c = tba.teamRequest;
                Event[] e = c.getEvents(2658);(the error seems to be  directed to this line)
                robot = c.getTeam(2658);

**Comment by spencerng** [comment]
Hi Sanjit,

I can't seem to reproduce the error on my end. Are you sure that your TBA API key is correct and your application has access to the Internet? 

A copy of your source code would also be useful in debugging your program.

**Comment by Sanjit1** [comment]
My key is correct, and my app has access to the internet. The java file is 
https://github.com/Sanjit1/FRCScouter/blob/master/app/src/main/java/io/github/sanjit1/frcscouter/teams.java 
The error comes around line 75

**Comment by spencerng** [comment]
In an Android app, you will generally need to create an [Asynchronous Task](https://developer.android.com/reference/android/os/AsyncTask) in order to access the Internet, rather than executing code in the UI thread. This may be the cause of your error. An implementation can be found [in Team 25's scouting app here](https://github.com/RaiderRobotix/Scouting-App/blob/master/scoutingapp/src/main/java/org/usfirst/frc/team25/scouting/data/thebluealliance/DataDownloader.java).

**Comment by Sanjit1** [comment]
OK I understood, Thanks so much!
