### ISSUE TITLE
Trying to get teams from an event throws IllegalAccessException

### ISSUE THREAD

**Issue by NicholasBottone** [RaiderRobotix/blue-alliance-api-java-library#4]
When calling `getTeams` on an `EventRequest`, the JSON parser will invoke the wrong constructor for `Team` and result in an `IllegalAccessException`.

https://github.com/RaiderRobotix/blue-alliance-api-java-library/blob/master/src/main/java/com/thebluealliance/api/v3/requests/EventRequest.java#L57
https://github.com/RaiderRobotix/blue-alliance-api-java-library/blob/master/src/main/java/com/thebluealliance/api/v3/models/Team.java#L17

```
java.lang.RuntimeException: Failed to invoke com.thebluealliance.api.v3.models.Team() throws java.lang.IllegalAccessException with no args
    at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:118)
Caused by: java.lang.IllegalAccessException: You've called the constructor of Team
    at com.thebluealliance.api.v3.models.Team.<init>(Team.java:17)
```

**Comment by hybras** [comment]
Hello @NicholasBottone. This is an alpha release. Thank you for catching this bug. I have made the constructors of this class and Match assign default values to all parameters. These are the two classes which used inheritance to avoid code duplication (the properties of Team and Match are supersets of SimpleTeam and SimpleMatch). I believed (incorrectly) the gson did not call the constructor of a deserialized class. Please report if this or similar errors still occur.

In order to grab the testing version of this lib change the version you are using to "3.0.1".
